### ISSUE TITLE
fix docker install playbook

### ISSUE THREAD

**Issue by lmilbaum** [bregman-arie/dpline#27]
environment spawning - ./dpline-env.sh

docker install playbook is broken

**Comment by lioramilbaum** [comment]
@bregman-arie can we use this role instead?
https://github.com/geerlingguy/ansible-role-docker

**Comment by bregman-arie** [comment]
> @bregman-arie can we use this role instead?
> https://github.com/geerlingguy/ansible-role-docker
Fine by me.

**Comment by bregman-arie** [comment]
I'll need more information to work on this. "docker install playbook is broken" doesn't tells me what's the issue.

**Comment by lioramilbaum** [comment]
the broken issue will be handled by switching to a community role. review/merge the PR so I can continue from there.
